### ISSUE TITLE
Integration with Helix

### ISSUE THREAD

**Issue by Mawfyy** [mattwparas/steel#225] opened 2024-06-23 03:07 UTC
Hello, I appreciate your work with Steel and as a Plugin system!

Testing the plugin system (great work btw) I founded a misunderstanding about how to integrate this with Helix.

In STEEL.md (https://github.com/mattwparas/helix) you mentioned using the master branch on steel, but in the master branch it has a conflict with steel-core dependency

Helix fork:
![image](https://github.com/mattwparas/steel/assets/94380448/8e509252-d72a-43d0-a73c-e38dea55bffc)

Steel:
![image](https://github.com/mattwparas/steel/assets/94380448/c3d0adc9-dfd4-4376-ba1e-4f28fc7b4793)

**Comment by mattwparas** [comment] 2024-06-23 03:52
Thanks for opening this, I'll take a look and update things accordingly

**Comment by mattwparas** [comment] 2024-06-23 04:04
Looks like there is an issue with the master branch of steel at the moment that is causing some things to not work correctly, once I can figure it out I'll make sure that the instructions are lined up with the latest work

**Comment by Mawfyy** [comment] 2024-06-23 04:08
Thanks, I appreciate your time and effort!

**Comment by mattwparas** [comment] 2024-06-23 04:42
Looks like #217 introduced a regression, I'm investigating

@jrvidal FYI - something strange where we're losing things that are multi arity across module boundaries.

**Comment by jrvidal** [comment] 2024-06-23 05:05
I might have time to take a look into it today. Any other details about it?

**Comment by mattwparas** [comment] 2024-06-23 05:07
Trying to reproduce as minimally as possible, within helix it is much harder to debug. I'll update here once I get somewhere

**Comment by mattwparas** [comment] 2024-06-23 05:21
For the sake of clarify, if you have a working build of steel + helix on the latest master, trying to use any of the functions from `helix/commands.scm` seems to fail. All of them are generated to be multi arity, like so:

```scheme
(provide theme)

;;@doc
;;Change the editor theme (show current theme if no name specified).
(define (theme . args)
  (helix.theme *helix.cx* args))
```

But attempting to use those by importing like so:

```scheme
(require (prefix-in hx. "helix/commands.scm"))

(hx.theme "boo_berry")
```

raises an error due to the arguments not getting wrapped in a list. `(multi-arity hx.theme)` returns `#f`, so it seems _somewhere_ along the line, we're losing the fact that it should accept multiple arguments.

I'm still trying to reproduce outside of helix

**Comment by mattwparas** [comment] 2024-06-23 06:18
Reasonably confident that the issue is here: https://github.com/mattwparas/steel/blob/master/crates/steel-parser/src/parser.rs#L475

Basically when we parse without lowering, we then just lose the fact that the list is improper. Trying to hack in adding that information back quickly to see if it does the trick

**Comment by jrvidal** [comment] 2024-06-23 07:25
I think I found it, it's something in the parsing stage.

**Comment by jrvidal** [comment] 2024-06-23 08:29
OK, no, I was wrong. It's something about macro expansion. The `improper: true` field is lost after [this call](https://github.com/mattwparas/steel/blob/master/crates/steel-core/src/parser/expand_visitor.rs#L226). So it seems macro expansion matters more that I initially thought :disappointed: 

FWIW I think reverting is totally fine until we're more confident that the change is sound.

**Comment by jrvidal** [comment] 2024-06-23 08:38
More concretely, the problem is with the `@doc` macro :facepalm:

**Comment by mattwparas** [comment] 2024-06-23 13:58
Ah good catch! Looks like I need some more tests around that.

I'll see if I can plumb the improper field through, or quickly add support before reverting

**Comment by mattwparas** [comment] 2024-06-23 15:26
Also - thanks for investigating! Getting it down to the macro expansion line is super helpful, I'm looking over the code to see how hard it would be to just add support for improper lists there now. Realistically I don't think its _too_ hard, but famous last words of course :smile:

**Comment by mattwparas** [comment] 2024-06-23 18:00
Everything _should_ be fixed now as per #226 - I've also updated the instructions for helix. Check the branch `steel-event-system` on my fork of helix, the toml has been updated

**Comment by Mawfyy** [comment] 2024-06-29 16:27
Thanks for your time and effort!

I get other bug related with keybindings module...

![image](https://github.com/mattwparas/steel/assets/94380448/e87fb2a3-a0e0-40c5-a278-17e4d6e0d7bb)

**Comment by mattwparas** [comment] 2024-06-29 16:30
Sheesh, sorry about that, I forgot to update those as well.

In the mean time while I update those, this is going to be the most concrete source of truth: https://github.com/mattwparas/helix-config/blob/master/helix.scm

That repo has my entire helix config, which is pretty much guaranteed to work since I daily drive off of it

**Comment by Mawfyy** [comment] 2024-06-29 16:34
Okay, i gonna check it, thanks!

**Comment by mattwparas** [comment] 2024-06-29 16:39
Just updated the instructions, although I haven't tested them extensively, I just more or less copied over some minimal examples from my helix config directly

**Comment by Mawfyy** [comment] 2024-06-29 16:40
I tried copy your configuration to .config/helix and i did execute `cargo xtask code-gen`
and i get this
![image](https://github.com/mattwparas/steel/assets/94380448/41224db3-7d5f-4378-9411-7987207f5d3a)

**Comment by mattwparas** [comment] 2024-06-29 16:42
So in `helix.scm` just comment out these lines:

```scheme
(require "term.scm")

(provide open-term
         new-term
         kill-active-terminal
         switch-term
         term-resize
         xplr
         open-debug-window
         close-debug-window)

```

**Comment by Mawfyy** [comment] 2024-06-29 21:58
It works, thank you so much!

Also, i would like to update the documentation ^^

**Closed** 2024-06-29 22:58 UTC
